Support WindowsStore builds for ROS2
ros2/libyaml_vendor pull request #50
Opened 2022-04-14 21:22 UTC by ooeygui

This is a make file change which affects the Win32 build blocks, specifically this change forwards passed in CMAKE_SYSTEM_NAME and CMAKE_SYSTEM_VERSION, which are needed to pass the Windows Store system, required to run ROS2 on a Hololens. 

Without this change, libyaml is not built with a Windows container safe API set and fails to load when included in UWP and Hololens applications.

2022-05-05 14:08 UTC, clalancette requested changes
One nit to fix, then I think this will be ready for CI.

2022-05-05 14:08 UTC, clalancette commented on CMakeLists.txt
> +
Nit: no need for this extra whitespace.

2022-05-05 21:01 UTC, ooeygui commented on CMakeLists.txt
> +
Good catch - sorry about that!

2022-05-05 21:02 UTC, clalancette approved these changes
Looks good, thanks for iterating.  I'll run CI on it next.

2022-05-05 21:02 UTC, clalancette commented
Oh, it looks like you need to rebase and fix signed-off lines for the DCO bot.  Once that is done, I'll run CI.

2022-05-09 12:49 UTC, clalancette commented
CI:
* Linux [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux&build=16665)](http://ci.ros2.org/job/ci_linux/16665/)
* Linux-aarch64 [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux-aarch64&build=11251)](http://ci.ros2.org/job/ci_linux-aarch64/11251/)
* Windows [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_windows&build=17060)](http://ci.ros2.org/job/ci_windows/17060/)

2022-05-09 18:20 UTC, clalancette commented
The failing test on Linux is flaky.  With that, going ahead and merging this.

2022-05-09 18:20 UTC, merged