Vendor same version as Jammy (v0.2.2)
ros2/libyaml_vendor pull request #57
Opened 2023-04-07 16:27 UTC by Yadunund

This PR switches the version of libyaml vendored from `0.2.5` to `0.2.2`, ie the same version as [debian in Jammy](https://packages.ubuntu.com/jammy/libyaml-dev) It also forces build if the version of the system package is greater than `0.2.2`.

CI:
* Linux [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux&build=18470)](http://ci.ros2.org/job/ci_linux/18470/)
* Linux-aarch64 [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux-aarch64&build=13017)](http://ci.ros2.org/job/ci_linux-aarch64/13017/)
* RHEL-9 [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux-rhel&build=375)](http://ci.ros2.org/job/ci_linux-rhel/375/)
* Windows [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_windows&build=19178)](http://ci.ros2.org/job/ci_windows/19178/)

2023-04-20 17:29 UTC, clalancette requested changes

2023-04-20 17:29 UTC, clalancette commented on CMakeLists.txt
> +    set(_SKIP_YAML_BUILD 0)
We discussed this in the Waffle meeting today.  The general feeling was that it is OK to enforce a maximum, but we probably shouldn't do it so strictly.  For instance, our rosdep keys don't make this enforcement.  So the suggestion here is to only build locally if the system version is greater than the next minor version, i.e. this check should be `>= 0.3.0`.

2024-07-22 13:56 UTC, mjcarroll commented
@Yadunund what is the status of this?  Since rolling is no longer on Jammy, does it make sense to apply this?

2024-07-22 14:29 UTC, clalancette commented
> @Yadunund what is the status of this? Since rolling is no longer on Jammy, does it make sense to apply this?

Ah yes, good call.  We already updated this to 0.2.5 to match Ubuntu 24.04, so we can close this out.

2024-07-22 14:29 UTC, closed without merging